apiVersion: v1
kind: ResourceQuota
metadata:
  name: myapp-quota
  namespace: default
spec:
  hard:
    pods: "6"
    requests.cpu: "600m"
    requests.memory: "384Mi"
    limits.cpu: "1500m"
    limits.memory: "768Mi"
